### PR TITLE
Clarify angle units in documentation

### PR DESCRIPTION
**Pull request by mariapana**
The PR aims to clarify which angle unit functions use, since there are some that use radians and others that use degrees. Based on the current documentation alone, a new user may not be certain what the correct input/output should look like. After researching the topic and looking into the function definitions, I added notes on what angle unit was used for each related function.

The modified files are:

* `src/geometry/rotation_specialization.rs`
* `src/geometry/rotation_specialization.rs`
* `src/base/matrix.rs`

Based on: https://github.com/dimforge/nalgebra/issues/1234

### CODE REVIEW

**Comment by alexandruradovici** [comment]
This seems to have a lot of modified files, can you clarify what this pull request does?

**Comment by mariapana** [comment]
The PR aims to clarify which angle unit functions use, since there are some that use radians and others that use degrees. Based on the current documentation alone, a new user may not be certain what the correct input/output should look like. After researching the topic and looking into the function definitions, I added notes on what angle unit was used for each related function.

The modified files are:
* `src/geometry/rotation_specialization.rs`
* `src/geometry/rotation_specialization.rs`
* `src/base/matrix.rs`

**Comment by alexandruradovici** [comment]
Please put the text in the pull request description.

**Comment by alexandruradovici** [comment]
This seems to have many modifications, could this be due to clippy?

**Comment by mariapana** [comment]
I have made only 3 modifications (regarding the files mentioned in the description). The rest I believe are due to the UPB-CS-OpenSourceUpstream's repository being a few commits behind the main repository.

**Comment by alexandruradovici** [comment]
Please rebase your PR, I updated the repo.

**Pull request closed without merging**
